### ISSUE TITLE
Syntax error in CodeRefactoringProvider.cs

### ISSUE THREAD

**Issue by ddagsan** [conwid/DependencyInjectionToolset#6]
I'm using VS2015 and getting the followinr error in CodeRefactoringProvider.cs
![image](https://user-images.githubusercontent.com/5840428/35030911-d10ff4a6-fb71-11e7-9da1-2acbe7d669bb.png)

**Comment by conwid** [comment]
Thanks for reporting the issue. You're getting this syntax error because your are using VS2015, which probably uses the C# 5.0 compiler by default and the pattern matching feature that's used in the if block was introduced in C# 6.0.
Please upgrade your Visual Studio or make sure to use the C# 6.0 compiler.
